import React from "react";
import classNames from "classnames";
import { SectionProps } from "../../utils/SectionProps";

import { GANS_MIDI_FILES, EVO_MIDI_FILES, REAL_MIDI_FILES, EVO_SPECS } from "../../constants";
import MelodyCarousel from "./MelodyCarousel";

const defaultProps = {
  ...SectionProps.defaults,
};

const MelodyEvidences = ({
  className,
  topOuterDivider,
  bottomOuterDivider,
  topDivider,
  bottomDivider,
  hasBgColor,
  invertColor,
  ...props
}) => {
  const outerClasses = classNames(
    "hero section center-content",
    topOuterDivider && "has-top-divider",
    bottomOuterDivider && "has-bottom-divider",
    hasBgColor && "has-bg-color",
    invertColor && "invert-color",
    className
  );

  const innerClasses = classNames(
    "hero-inner section-inner",
    topDivider && "has-top-divider",
    bottomDivider && "has-bottom-divider"
  );

  return (
    <section {...props} className={outerClasses}>
      <div className="container-sm">
        <div className={innerClasses}>
          <div className="hero-content">
            <h1
              className="mt-0 mb-16 reveal-from-bottom"
              data-reveal-delay="200"
            >
              GAN + EVO
            </h1>
            <MelodyCarousel midiFiles={EVO_MIDI_FILES} evoSpecs={EVO_SPECS} headerText={'Melodies generated by the GAN + Evolutionary Algorithm'}/>
            <h1
              className="mt-0 mb-16 reveal-from-bottom"
              data-reveal-delay="200"
            >
              GAN
            </h1>
            <MelodyCarousel midiFiles={GANS_MIDI_FILES} headerText={'Melodies generated by the GAN'}/>
            <h1
              className="mt-0 mb-16 reveal-from-bottom"
              data-reveal-delay="200"
            >
              Training data
            </h1>
            <MelodyCarousel midiFiles={REAL_MIDI_FILES} headerText={'Melodies generated by training data'}/>
          </div>
          <div
            className="hero-figure reveal-from-bottom illustration-element-01"
            data-reveal-value="20px"
            data-reveal-delay="800"
          ></div>
        </div>
      </div>
    </section>
  );
};

MelodyEvidences.defaultProps = defaultProps;

export default MelodyEvidences;
